### ISSUE TITLE
new netgraph major release

### ISSUE THREAD

**Issue by paulbrodersen** [ronikobrosly/DAG_from_GNN#1]
Hi,

I saw on the github dashboard that you are using my package netgraph.

This is a heads up that I just released a new major version. I tried to maintain backwards compatibility as much as possible but I did break it in a few cases. Especially if your code uses either the `Graph` or `InteractiveGraph` classes, expect a few changes. Also, I have removed some InteractiveGraph derived variants for the time being, as they seem to be used very little but are a pain to maintain. If that affects you, please let me know, so we can work something out.

Hopefully, you will find that the improvements that I have made are worth any pains that might arise from upgrading. ;-)

Best,
Paul

PS: Feel free to close the issue any time.

**Comment by ronikobrosly** [comment]
Thanks so much for the heads up @paulbrodersen !
